import logging
import pathlib
from textwrap import dedent

import pytest

from activate_django_first import EMG_CONFIG

from analyses.models import Run, Study
from workflows.flows.analyse_study_tasks.shared.dwcr_generator import (
    generate_dwc_ready_summary_for_pipeline_run,
    merge_dwc_ready_summaries,
)


def _ensure_flow_like_amplicon_objects_for_dwcr(study: Study):
    """
    Ensure the minimum Study/Sample/Run metadata exists as it would after
    `analysis_amplicon_study` ingests run data from ENA.

    Assumes a Run (e.g. from the `amplicon_analysis_with_downloads` fixture)
    already exists for the study.
    """
    sample_metadata = {
        "lat": 52,
        "lon": 0,
        "collection_date": "2025-05-25",
        "depth": 0.12,
        "center_name": "Devonshire Building",
        "temperature": 12,
        "salinity": 0.12,
        "country": "United Kingdom",
    }

    study.inherit_accessions_from_related_ena_object("ena_study")

    run = study.runs.select_related("sample__ena_sample").get()

    sample = run.sample
    sample.studies.add(study)
    sample.inherit_accessions_from_related_ena_object("ena_sample")
    sample.metadata.update(sample_metadata)
    sample.save()

    run.instrument_platform = run.instrument_platform or "ILLUMINA"
    run.instrument_model = run.instrument_model or "Illumina MiSeq"
    run.experiment_type = Run.ExperimentTypes.AMPLICON
    run.save()


@pytest.mark.django_db(transaction=True)
def test_dwcr_generator(
    amplicon_analysis_with_downloads,
    raw_reads_mgnify_study: Study,
    prefect_harness,
    completed_runs_filename: str = EMG_CONFIG.amplicon_pipeline.completed_runs_csv,
):
    amplicon_pipeline_outdir = pathlib.Path(
        amplicon_analysis_with_downloads.pipeline_outdir
    )
    refdb_otus = pathlib.Path(EMG_CONFIG.amplicon_pipeline.refdb_otus_dir)

    # Ensure there is at least one Run/Sample for the study so the generator
    # can build per-run metadata JSON. Create minimal ENA and analysis objects
    # when the study has no runs.
    _ensure_flow_like_amplicon_objects_for_dwcr(raw_reads_mgnify_study)

    # qc_passed_runs.csv also lists SRR6180434, which has no amplicon results and will be skipped by the generator.
    # However, it should be present in JSON metadata.
    # Give it a placeholder object referencing existing sample so the generator
    # finds metadata for both runs.
    placeholder_sample = raw_reads_mgnify_sample[1]
    placeholder_sample.studies.add(raw_reads_mgnify_study)
    Run.objects.get_or_create(
        ena_accessions=["SRR6180434"],
        study=raw_reads_mgnify_study,
        ena_study=raw_reads_mgnify_study.ena_study,
        sample=placeholder_sample,
        experiment_type=Run.ExperimentTypes.AMPLICON,
    )

    generate_dwc_ready_summary_for_pipeline_run(
        raw_reads_mgnify_study.accession,
        amplicon_pipeline_outdir,
        refdb_otus,
        completed_runs_filename,
    )


@pytest.mark.django_db(transaction=True)
def test_dwcr_merge(
    raw_reads_mgnify_study: Study,
    prefect_harness,
):
    prj_accession = "PRJNA398089"

    amplicon_folder = pathlib.Path(
        f"{EMG_CONFIG.slurm.default_workdir}/{prj_accession}/amplicon_v6"
    )
    amplicon_folder.mkdir(exist_ok=True, parents=True)
    logging.info(amplicon_folder)
    logging.info(amplicon_folder.exists())

    summaries_folder = amplicon_folder / "summaries"
    summaries_folder.mkdir(exist_ok=True, parents=True)
    logging.info(summaries_folder)
    logging.info(summaries_folder.exists())

    # create fake dwcr files for testing
    with open(
        summaries_folder / "abc123_DADA2_SILVA_16S-V3-V4_dwcready.csv", "w"
    ) as fw:
        fw.write(dedent("""\
        ASVID,StudyID,SampleID,RunID,decimalLongitude,decimalLatitude,depth,temperature,salinity,collectionDate,seq_meth,country,InstitutionCode,amplifiedRegion,ASVCaller,ReferenceDatabase,TaxAnnotationTool,Superkingdom,Kingdom,Phylum,Class,Order,Family,Genus,Species,taxonID,MeasurementUnit,MeasurementValue,dbhit,dbhitIdentity,dbhitStart,dbhitEnd,ASVSeq
        seq_1,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Pseudomonadota,Alphaproteobacteria,Hyphomicrobiales,Nitrobacteraceae,Bradyrhizobium,NA,374,Number of reads,308,HE818674.1.1466,1.0,284,686,TGGGGAATATTGGACAATGGGCGCAAGCCTGATCCAGCCATGCCGCGTGAGTGATGAAGGCCCTAGGGTTGTAAAGCTCTTTTGTGCGGGAAGATAATGACGGTACCGCAAGAATAAGCCCCGGCTAACTTCGTGCCAGCAGCCGCGGTAATACGAAGGGGGCTAGCGTTGCTCGGAATCACTGGGCGTAAAGGGTGCGTAGGCGGGTCTTTAAGTCAGGGGTGAAATCCTGGAGCTCAACTCCAGAACTGCCTTTGATACTGAGGATCTTGAGTTCGGGAGAGGTGAGTGGAACTGCGAGTGTAGAGGTGAAATTCGTAGATATTCGCAAGAACACCAGTGGCGAAGGCGGCTCACTGGCCCGATACTGACGCTGAGGCACGAAAGCGTGGGGAGCAAACA
        seq_10,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Acidobacteriota,NA,NA,NA,NA,NA,57723,Number of reads,153,JN023865.1.1456,1.0,293,695,TGGGGAATTTTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGGAGGATGAAGCCCCTTGGGGTGTAAACTCCTTTCGACCGGGAAAATAATGATGGTACCGGTGGAAGAAGCACCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGTGCGAGCGTTGTTCGGAATTATTGGGCGTAAAGGGCGCGTAGGCGGTGTTGTAAGTCACCTGTGAAACCTCTGGGCTTAACTCAGAGCCTGCAGGCGAAACTGCAATGCTGGAGGGTGGGAGAGGTGCGTGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAGGAACACCTGTGGCGAAAGCGGCGCACTGGACCACTACTGACGCTGAGGCGCGAAAGCTAGGGGAGCAAACA
        seq_101,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Actinomycetota,Actinomycetes,Acidothermales,Acidothermaceae,Acidothermus,NA,28048,Number of reads,48,JF095799.1.1337,0.9901719689369202,324,731,TGGGGAATATTGCGCAATGGGCGGAAGCCTGACGCAGCGACGCCGCGTGCGGGATGAAGGCCTTCGGGTTGTAAACCGCTTTCACCAGGGACGAAGCGGAAGTGACGGTACCTGGGGAAGAAGCGCCGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGGCGCGAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGCGGCTGGTTGCGTCTGCTGTGAAATCCCGGGGCTTAACCCCGGGCGTGCAGTGGATACGGGCCGGCTGGAGGCAGGCAGGGGAGAATGGAATTCCCGGTGTAGCGGTGAAATGCGCAGATATCGGGAGGAACACCGGTGGCGAAGGCGGTTCTCTGGGCCTGTACTGACGCTGAGGAGCGAAAGCGTGGGGAGCAAACA
        seq_102,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Acidobacteriota,Terriglobia,Terriglobales,Acidobacteriaceae,NA,bacterium_Ellin327,204666,Number of reads,45,AF498709.1.1397,1.0,325,727,TGGGGAATTTTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGGAGGATGAAGTCCCTTGGGATGTAAACTCCTTTCGATCGGGACGATTATGACGGTACCGGAAGAAGAAGCACCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGTGCAAGCGTTGTTCGGAATTATTGGGCGTAAAGGGTGCGTAGGCGGTGCGGTAAGTCTGTAGTGAAATCTCTGGGCTCAACTCAGAGTCTGCTATAGAAACTGCCGTGCTAGAGTGTGGGAGAGGTGAGTGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAGGAACACCTGTGGCGAAAGCGGCTCACTGGACCACAACTGACGCTGATGCACGAAAGCTAGGGGAGCAAACA
        seq_103,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Acidobacteriota,NA,NA,NA,NA,NA,57723,Number of reads,45,GQ339135.1.1517,0.9953271150588988,360,788,TGAGGAATCTTGCGCAATGGGCGAAAGCCTGACGCAGCGACGCCGCGTGGAGGATGAAGGTCTTCGGATTGTAAACTCCTGTCGAGTGGGACGAATGCCGTGAGGGTGAACAATCCTTACGGTTGACGGTACCGCTGGAGGAAGCCCCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGGGCTAGCGTTGTTCGGAATCATTGGGCGTAAAGGGCGCGTAGGCGGCCGATCAAGTCGGAGGTGAAATCCCTCGGCTCAACTGAGGAATTGCCTTCGATACTGTTCGGCTTGAGTCCTGGAGAGGGTAGCGGAATTCCCGGTGTAGCGGTGAAATGCGTAGAGACCGGGAAGAACACCAGTGGCGAAGGCGGCTACCTGGACAGGTACTGACGCTGAAGCGCGAAAGCTAGGGGAGCAAACA
                """))

    with open(
        summaries_folder / "def456_DADA2_SILVA_16S-V3-V4_dwcready.csv", "w"
    ) as fw:
        fw.write(dedent("""\
        ASVID,StudyID,SampleID,RunID,decimalLongitude,decimalLatitude,depth,temperature,salinity,collectionDate,seq_meth,country,InstitutionCode,amplifiedRegion,ASVCaller,ReferenceDatabase,TaxAnnotationTool,Superkingdom,Kingdom,Phylum,Class,Order,Family,Genus,Species,taxonID,MeasurementUnit,MeasurementValue,dbhit,dbhitIdentity,dbhitStart,dbhitEnd,ASVSeq
        seq_1,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Pseudomonadota,Alphaproteobacteria,Hyphomicrobiales,Nitrobacteraceae,Bradyrhizobium,NA,374,Number of reads,308,HE818674.1.1466,1.0,284,686,TGGGGAATATTGGACAATGGGCGCAAGCCTGATCCAGCCATGCCGCGTGAGTGATGAAGGCCCTAGGGTTGTAAAGCTCTTTTGTGCGGGAAGATAATGACGGTACCGCAAGAATAAGCCCCGGCTAACTTCGTGCCAGCAGCCGCGGTAATACGAAGGGGGCTAGCGTTGCTCGGAATCACTGGGCGTAAAGGGTGCGTAGGCGGGTCTTTAAGTCAGGGGTGAAATCCTGGAGCTCAACTCCAGAACTGCCTTTGATACTGAGGATCTTGAGTTCGGGAGAGGTGAGTGGAACTGCGAGTGTAGAGGTGAAATTCGTAGATATTCGCAAGAACACCAGTGGCGAAGGCGGCTCACTGGCCCGATACTGACGCTGAGGCACGAAAGCGTGGGGAGCAAACA
        seq_10,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Acidobacteriota,NA,NA,NA,NA,NA,57723,Number of reads,153,JN023865.1.1456,1.0,293,695,TGGGGAATTTTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGGAGGATGAAGCCCCTTGGGGTGTAAACTCCTTTCGACCGGGAAAATAATGATGGTACCGGTGGAAGAAGCACCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGTGCGAGCGTTGTTCGGAATTATTGGGCGTAAAGGGCGCGTAGGCGGTGTTGTAAGTCACCTGTGAAACCTCTGGGCTTAACTCAGAGCCTGCAGGCGAAACTGCAATGCTGGAGGGTGGGAGAGGTGCGTGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAGGAACACCTGTGGCGAAAGCGGCGCACTGGACCACTACTGACGCTGAGGCGCGAAAGCTAGGGGAGCAAACA
        seq_101,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Actinomycetota,Actinomycetes,Acidothermales,Acidothermaceae,Acidothermus,NA,28048,Number of reads,48,JF095799.1.1337,0.9901719689369202,324,731,TGGGGAATATTGCGCAATGGGCGGAAGCCTGACGCAGCGACGCCGCGTGCGGGATGAAGGCCTTCGGGTTGTAAACCGCTTTCACCAGGGACGAAGCGGAAGTGACGGTACCTGGGGAAGAAGCGCCGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGGCGCGAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGCGGCTGGTTGCGTCTGCTGTGAAATCCCGGGGCTTAACCCCGGGCGTGCAGTGGATACGGGCCGGCTGGAGGCAGGCAGGGGAGAATGGAATTCCCGGTGTAGCGGTGAAATGCGCAGATATCGGGAGGAACACCGGTGGCGAAGGCGGTTCTCTGGGCCTGTACTGACGCTGAGGAGCGAAAGCGTGGGGAGCAAACA
        seq_102,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Acidobacteriota,Terriglobia,Terriglobales,Acidobacteriaceae,NA,bacterium_Ellin327,204666,Number of reads,45,AF498709.1.1397,1.0,325,727,TGGGGAATTTTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGGAGGATGAAGTCCCTTGGGATGTAAACTCCTTTCGATCGGGACGATTATGACGGTACCGGAAGAAGAAGCACCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGTGCAAGCGTTGTTCGGAATTATTGGGCGTAAAGGGTGCGTAGGCGGTGCGGTAAGTCTGTAGTGAAATCTCTGGGCTCAACTCAGAGTCTGCTATAGAAACTGCCGTGCTAGAGTGTGGGAGAGGTGAGTGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAGGAACACCTGTGGCGAAAGCGGCTCACTGGACCACAACTGACGCTGATGCACGAAAGCTAGGGGAGCAAACA
        seq_103,ERP122862,SAMEA7057179,ERR4334351,10.408889,51.112278,0.1,NA,NA,2018-05-02,Illumina MiSeq,Germany,FRIEDRICH SCHILLER UNIVERSITY JENA,16S-V3-V4,DADA2,SILVA,MAPseq,Bacteria,NA,Acidobacteriota,NA,NA,NA,NA,NA,57723,Number of reads,45,GQ339135.1.1517,0.9953271150588988,360,788,TGAGGAATCTTGCGCAATGGGCGAAAGCCTGACGCAGCGACGCCGCGTGGAGGATGAAGGTCTTCGGATTGTAAACTCCTGTCGAGTGGGACGAATGCCGTGAGGGTGAACAATCCTTACGGTTGACGGTACCGCTGGAGGAAGCCCCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGGGCTAGCGTTGTTCGGAATCATTGGGCGTAAAGGGCGCGTAGGCGGCCGATCAAGTCGGAGGTGAAATCCCTCGGCTCAACTGAGGAATTGCCTTCGATACTGTTCGGCTTGAGTCCTGGAGAGGGTAGCGGAATTCCCGGTGTAGCGGTGAAATGCGTAGAGACCGGGAAGAACACCAGTGGCGAAGGCGGCTACCTGGACAGGTACTGACGCTGAAGCGCGAAAGCTAGGGGAGCAAACA
                """))

    merge_dwc_ready_summaries(raw_reads_mgnify_study.accession, False, True)
