[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "emgapiv2.settings_test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
markers = [
    "dev_data_maker: A test that is not really a test but used to generate data for dev purposes"
]
addopts = "--cov=/app --cov-report=term-missing --cov-report=html:coverage/htmlcov --cov-report=xml:coverage/coverage.xml -m 'not dev_data_maker'"
env = [
    "EMG_WEBIN__EMG_WEBIN_ACCOUNT=Webin-000",
    "EMG_WEBIN__EMG_WEBIN_PASSWORD=password",
]
filterwarnings = "ignore:.*is deprecated:DeprecationWarning"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
omit = ["*/tests/*", "*/migrations/*", "*settings*", "*asgi.py", "*wsgi.py", "*make_dev_data.py"]

[tool.ruff.lint]
ignore = ["E402"]  # allow imports after django.setup()
exclude = ["emgapiv2/settings_test.py"]
