[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "emgapiv2.settings_test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "--cov=/app --cov-report=term-missing --cov-report=html --cov-report=xml"
