---
version: '3'

includes:
  ebi-wp-k8s-hl:
    taskfile: ./deployment/ebi-wp-k8s-hl/Taskfile.yaml
    dir: ./deployment/ebi-wp-k8s-hl

tasks:
  prefect:
    desc: "Run a command on the prefect CLI. E.g. task prefect -- deployment"
    cmds:
      - docker compose run app prefectcli {{.CLI_ARGS}}

  create-pool:
    desc: "Create a Prefect workpool. E.g. NAME=slurm task create-process-pool"
    cmds:
      - docker compose exec app python manage.py prefectcli work-pool create --annotation_type {{.TYPE}} {{.CLI_ARGS}} {{.NAME}}
    vars:
      TYPE: "process"
      NAME: "slurm"
      TEMPLATE: "./slurm/base-job-templates/local-slurm-job-template.json"

  deploy-flow:
    desc: "Build and deploy a prefect flow. E.g. FLOW=mgnify_run_pipeline_flow task deploy-flow"
    cmds:
      - docker compose --profile prefect up -d
      - docker compose run app prefectcli deployment build workflows/flows/{{.FLOW}}.py:{{.FLOW}} --name {{.FLOW}}_deployment --output workflows/deployments/{{.FLOW}}_deployment.yaml -p {{.POOL}} --apply
      - docker compose --profile prefect --profile app down
    vars:
      POOL: "slurm"
    requires:
      vars: [FLOW]

  deploy-utils:
    desc: "Build and deploy the Prefect/Slurm util flows."
    cmds:
      - docker compose --profile prefect up -d
      - docker compose run app prefectcli deployment build workflows/prefect_utils/slurm_flow.py:monitor_cluster --name monitor_slurm_cluster_deployment --output workflows/deployments/monitor_slurm_cluster_deployment.yaml -p slurm --apply --interval 60
      - docker compose --profile prefect --profile app down

  run:
    desc: "Run everything"
    cmds:
      - docker compose --profile all up

  manage:
    desc: "Run a management command. E.g. task manage -- migrate"
    cmds:
      - docker compose run app {{.CLI_ARGS}}

  sbatch:
    desc: "Dispatch a slurm job to the mini slurm cluster. E.g. task sbatch -- --wait -t 0:00:30 --mem=10M --wrap=\"echo 'hello world'\" -o hello-world.out"
    cmds:

      - docker exec slurm_node "sbatch {{.CLI_ARGS}}"

  slurm:
    desc: "Connect to the slurm node to run commands there."
    cmds:
      - docker exec -it slurm_node bash
    interactive: true
