---
version: '3'

includes:
  ebi-wp-k8s-hl:
    taskfile: ./deployment/ebi-wp-k8s-hl/Taskfile.yaml
    dir: ./deployment/ebi-wp-k8s-hl

tasks:
  prefect:
    desc: "Run a command on the prefect CLI. E.g. task prefect -- deployment"
    cmds:
      - docker compose run app prefectcli {{.CLI_ARGS}}

  create-pool:
    desc: "Create a Prefect workpool. E.g. NAME=slurm task create-process-pool"
    cmds:
      - docker compose exec app python manage.py prefectcli work-pool create --annotation_type {{.TYPE}} {{.CLI_ARGS}} {{.NAME}}
    vars:
      TYPE: "process"
      NAME: "slurm"
      TEMPLATE: "./slurm/base-job-templates/local-slurm-job-template.json"

  deploy-flow:
    desc: "Build and deploy a prefect flow. E.g. FLOW=mgnify_run_pipeline_flow task deploy-flow"
    cmds:
      - docker compose --profile prefect up -d
      - docker compose run app prefectcli deployment build workflows/flows/{{.FLOW}}.py:{{.FLOW}} --name {{.FLOW}}_deployment --output workflows/deployments/{{.FLOW}}_deployment.yaml -p {{.POOL}} --apply
    vars:
      POOL: "slurm"
    requires:
      vars: [FLOW]

  run-flow:
    desc: "Run flow when prefect is already running"
    cmds:
      - docker compose --profile prefect up -d
      - docker compose exec app workflows/flows/{{.FLOW}}.py:{{.FLOW}} --name {{.FLOW}}_deployment --output workflows/deployments/{{.FLOW}}_deployment.yaml -p {{.POOL}} --apply
    vars:
      POOL: "slurm"
    requires:
      vars: [ FLOW ]

  deploy-utils:
    desc: "Build and deploy the Prefect/Slurm util flows."
    cmds:
      - docker compose run app prefectcli deployment build workflows/prefect_utils/slurm_flow.py:run_cluster_job --name run_cluster_job_deployment --output workflows/deployments/run_cluster_job_deployment.yaml -p slurm --apply

  run:
    desc: "Run everything"
    cmds:
      - docker compose --profile all up {{.CLI_ARGS}}

  stop:
    desc: "Stop everything"
    cmds:
      - docker compose --profile all down

  manage:
    desc: "Run a management command. E.g. task manage -- migrate"
    cmds:
      - docker compose run app {{.CLI_ARGS}}

  sbatch:
    desc: "Dispatch a slurm job to the mini slurm cluster. E.g. task sbatch -- --wait -t 0:00:30 --mem=10M --wrap=\"echo 'hello world'\" -o hello-world.out"
    cmds:
      - docker exec slurm_node "sbatch {{.CLI_ARGS}}"

  slurm:
    desc: "Connect to the slurm node to run commands there."
    cmds:
      - docker exec -it slurm_node bash
    interactive: true

  test:
    desc: "Run pytest tests. E.g. `task test` or `task test -- -k study`"
    cmds:
      - docker compose run --entrypoint /bin/bash app -c "pytest {{.CLI_ARGS}}"

  make-dev-data:
    desc: "Populate the app database with some demo data for development purposes"
    prompt: "This will delete all data in the database! Are you sure?"
    cmds:
      - docker compose run app flush
      - docker compose run app make_dev_data
      - docker compose run app createsuperuser --username emgdev --email emg@example.org
