# Generated by Django 5.1.6 on 2025-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0029_analysis_is_suppressed"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
