# Generated by Django 5.2.1 on 2025-07-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0047_superstudy_superstudyimage_superstudystudy_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superstudystudy",
            options={
                "verbose_name": "Study in Super Study",
                "verbose_name_plural": "Studies in Super Study",
            },
        ),
    ]
