# Generated by Django 5.2.1 on 2025-07-17 14:21

import analyses.models
import django.db.models.deletion
import emgapiv2.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0048_alter_superstudystudy_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pubmed_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=740)),
                ("published_year", models.SmallIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    emgapiv2.model_utils.JSONFieldWithSchema(
                        encoder=emgapiv2.model_utils._PydanticEncoder,
                        is_list=False,
                        schema=analyses.models.Publication.PublicationMetadata,
                        strict=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.CreateModel(
            name="StudyPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyses.publication",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="analyses.study"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="publication",
            name="studies",
            field=models.ManyToManyField(
                related_name="publications",
                through="analyses.StudyPublication",
                to="analyses.study",
            ),
        ),
    ]
