# Generated by Django 5.2.1 on 2025-07-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0049_publication_studypublication_publication_studies"),
        ("genomes", "0002_alter_genome_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperStudyGenomeCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genome_catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genomes.genomecatalogue",
                    ),
                ),
                (
                    "super_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyses.superstudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genome Catalogue in Super Study",
                "verbose_name_plural": "Genome Catalogues in Super Study",
                "unique_together": {("genome_catalogue", "super_study")},
            },
        ),
        migrations.AddField(
            model_name="superstudy",
            name="genome_catalogues",
            field=models.ManyToManyField(
                related_name="super_studies",
                through="analyses.SuperStudyGenomeCatalogue",
                to="genomes.genomecatalogue",
            ),
        ),
    ]
