# Generated by Django 5.2.7 on 2025-10-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0050_superstudygenomecatalogue_and_more"),
        ("ena", "0004_alter_sample_additional_accessions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="ena_sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses_samples",
                to="ena.sample",
            ),
        ),
    ]
