# Generated by Django 5.2.1 on 2025-10-15 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0050_superstudygenomecatalogue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyAnalysisBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_type", models.CharField(max_length=50)),
                ("results_dir", models.CharField(max_length=500)),
                ("total_analyses", models.IntegerField()),
                (
                    "prefect_flow_run_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_batches",
                        to="analyses.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Analysis Batch",
                "verbose_name_plural": "Study Analysis Batches",
            },
        ),
        migrations.CreateModel(
            name="AssemblyAnalysisBatch",
            fields=[
                (
                    "studyanalysisbatch_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="analyses.studyanalysisbatch",
                    ),
                ),
                (
                    "asa_samplesheet_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "virify_samplesheet_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "map_samplesheet_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "asa_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "virify_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "map_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "asa_flow_run_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "virify_flow_run_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "map_flow_run_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("asa_started_at", models.DateTimeField(blank=True, null=True)),
                ("asa_completed_at", models.DateTimeField(blank=True, null=True)),
                ("virify_started_at", models.DateTimeField(blank=True, null=True)),
                ("virify_completed_at", models.DateTimeField(blank=True, null=True)),
                ("map_started_at", models.DateTimeField(blank=True, null=True)),
                ("map_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("pipeline_versions", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Assembly Analysis Batch",
                "verbose_name_plural": "Assembly Analysis Batches",
            },
            bases=("analyses.studyanalysisbatch",),
        ),
        migrations.AddField(
            model_name="analysis",
            name="assembly_analysis_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assembly_analysis_set",
                to="analyses.assemblyanalysisbatch",
            ),
        ),
    ]
