# Generated by Django 5.2.7 on 2025-10-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0051_alter_sample_ena_sample"),
        ("ena", "0005_study_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="study",
            name="ena_study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses_studies",
                to="ena.study",
            ),
        ),
    ]
