# Generated by Django 5.2.7 on 2025-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0052_study_metadata_alter_study_ena_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="studies",
            field=models.ManyToManyField(related_name="samples", to="analyses.study"),
        ),
    ]
