# Generated by Django 5.2.7 on 2026-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0052_update_download_groups_to_pathways_and_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembly",
            name="runs",
            field=models.ManyToManyField(
                blank=True, related_name="assemblies_m2m", to="analyses.run"
            ),
        ),
    ]
