# Generated by Django 5.2.7 on 2025-10-16 10:22

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0053_alter_sample_studies"),
        ("ena", "0005_study_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="sample_title",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Func(
                    models.Value("sample_title"),
                    function="jsonb_extract_path_text",
                    template="(jsonb_extract_path_text(metadata, %(expressions)s))",
                ),
                null=True,
                output_field=models.TextField(),
            ),
        ),
        TrigramExtension(),
        migrations.AddIndex(
            model_name="sample",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sample_title"],
                name="idx_sample_title_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
