# Generated by Django 5.2.7 on 2025-10-16 10:28

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0054_sample_sample_title_sample_idx_sample_title_trgm"),
        ("ena", "0005_study_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="publication",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="idx_publication_title_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="idx_study_title_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
