# Generated by Django 5.2.7 on 2026-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0054_migrate_assembly_run_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assembly",
            name="run",
        ),
        migrations.AlterField(
            model_name="assembly",
            name="runs",
            field=models.ManyToManyField(
                blank=True, related_name="assemblies", to="analyses.run"
            ),
        ),
    ]
