# Generated by Django 5.2.7 on 2025-10-16 10:58

import django.db.models.deletion
from django.db import migrations, models


def set_sample_biomes_from_first_study(apps, schema_editor):
    """
    Set the biome field on each sample to point at the biome of the first related study.
    """
    Sample = apps.get_model("analyses", "Sample")

    # Get all samples that have studies
    samples = Sample.objects.prefetch_related("studies").all()

    samples_to_update = []
    for sample in samples:
        # Get the first study (if any)
        first_study = sample.studies.first()
        if first_study and first_study.biome:
            sample.biome = first_study.biome
            samples_to_update.append(sample)

    # Bulk update for efficiency
    if samples_to_update:
        Sample.objects.bulk_update(samples_to_update, ["biome"])


def reverse_sample_biomes(apps, schema_editor):
    """
    Clear the biome field on all samples (reverse operation).
    """
    Sample = apps.get_model("analyses", "Sample")
    Sample.objects.update(biome=None)


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0055_publication_idx_publication_title_trgm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="biome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analyses.biome",
            ),
        ),
        migrations.RunPython(set_sample_biomes_from_first_study, reverse_sample_biomes),
    ]
