# Generated by Django 5.2.7 on 2026-02-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0055_remove_assembly_run_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleRelatedSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("derived_from", "DERIVED_FROM"),
                            ("same_as", "SAME_AS"),
                            ("symbiont_of", "SYMBIONT_OF"),
                            ("composed_of", "COMPOSED_OF"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "declaring_sample",
                    models.ForeignKey(
                        help_text="The sample that declares the relationship to the related_sample.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declared_sample_related_samples",
                        to="analyses.sample",
                    ),
                ),
                (
                    "related_sample",
                    models.ForeignKey(
                        help_text="The sample that is related to the declaring_sample.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inferred_sample_related_samples",
                        to="analyses.sample",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sample",
            name="related_samples",
            field=models.ManyToManyField(
                blank=True,
                related_name="inversely_related_samples",
                through="analyses.SampleRelatedSample",
                through_fields=("declaring_sample", "related_sample"),
                to="analyses.sample",
            ),
        ),
        migrations.AddConstraint(
            model_name="samplerelatedsample",
            constraint=models.UniqueConstraint(
                fields=("declaring_sample", "related_sample"),
                name="unique_sample_relationships",
            ),
        ),
        migrations.AddConstraint(
            model_name="samplerelatedsample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("declaring_sample", models.F("related_sample")), _negated=True
                ),
                name="no_self_relations",
            ),
        ),
    ]
