# Generated by Django 5.2.7 on 2026-06-19 14:34

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0057_analysis_pipeline_version_v6_1"),
        ("ena", "0006_alter_sample_study"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assembly",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ena_accessions"], name="idx_assembly_ena_acc_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ena_accessions"], name="idx_run_ena_accessions_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ena_accessions"], name="idx_sample_ena_accessions_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ena_accessions"], name="idx_study_ena_accessions_gin"
            ),
        ),
    ]
