# Generated by Django 5.2.1 on 2025-10-24 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0050_superstudygenomecatalogue_and_more"),
        ("workflows", "0007_alter_orchestratedclusterjob_input_files_hashes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyAnalysisBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_type",
                    models.CharField(
                        choices=[
                            ("assembly_analysis", "Assembly Analysis"),
                            ("amplicon_analysis", "Amplicon Analysis"),
                            ("rawreads_analysis", "Raw Reads Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "workspace_dir",
                    models.CharField(
                        help_text="This is the base workspace root dir for this batch",
                        max_length=500,
                    ),
                ),
                ("total_analyses", models.IntegerField(default=0)),
                (
                    "prefect_flow_run_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "asa_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Assembly Analysis status for the batch",
                        max_length=20,
                    ),
                ),
                (
                    "virify_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="VIRIfy status for the batch",
                        max_length=20,
                    ),
                ),
                (
                    "map_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Mobilome Annotation Pipeline status for the batch",
                        max_length=20,
                    ),
                ),
                (
                    "asa_samplesheet_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "virify_samplesheet_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "map_samplesheet_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "asa_flow_run_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "virify_flow_run_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "map_flow_run_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("pipeline_versions", models.JSONField(blank=True, default=dict)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_batches",
                        to="analyses.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembly Analysis Batch",
                "verbose_name_plural": "Assembly Analysis Batches",
            },
        ),
        migrations.CreateModel(
            name="AssemblyAnalysisBatchAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asa_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Assembly Analysis status for the batch",
                        max_length=20,
                    ),
                ),
                (
                    "virify_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="VIRIfy status for the batch",
                        max_length=20,
                    ),
                ),
                (
                    "map_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Mobilome Annotation Pipeline status for the batch",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of this analysis within the batch"
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this analysis should be excluded from the batch",
                    ),
                ),
                (
                    "disabled_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for disabling this analysis",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_batches",
                        to="analyses.analysis",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_analyses",
                        to="workflows.assemblyanalysisbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Analysis Relation",
                "verbose_name_plural": "Batch Analysis Relations",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="assemblyanalysisbatch",
            name="analyses",
            field=models.ManyToManyField(
                blank=True,
                related_name="assembly_analysis_batches",
                through="workflows.AssemblyAnalysisBatchAnalysis",
                to="analyses.analysis",
            ),
        ),
        migrations.AddIndex(
            model_name="assemblyanalysisbatchanalysis",
            index=models.Index(
                fields=["batch", "order"], name="workflows_a_batch_i_02127a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assemblyanalysisbatchanalysis",
            unique_together={("batch", "analysis")},
        ),
        migrations.AddIndex(
            model_name="assemblyanalysisbatch",
            index=models.Index(
                fields=["asa_status"], name="workflows_a_asa_sta_f1895e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assemblyanalysisbatch",
            index=models.Index(
                fields=["virify_status"], name="workflows_a_virify__3194e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assemblyanalysisbatch",
            index=models.Index(
                fields=["map_status"], name="workflows_a_map_sta_d9f189_idx"
            ),
        ),
    ]
