# Generated by Django 5.2.7 on 2025-11-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0008_assemblyanalysisbatch_assemblyanalysisbatchanalysis_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assemblyanalysisbatchanalysis",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Batch Assembly Analysis",
                "verbose_name_plural": "Batch Assembly Analyses",
            },
        ),
    ]
