# Generated by Django 5.2.7 on 2025-11-07 15:10

import emgapiv2.model_utils
import workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0009_alter_assemblyanalysisbatchanalysis_options"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assemblyanalysisbatch",
            name="workflows_a_asa_sta_f1895e_idx",
        ),
        migrations.RemoveIndex(
            model_name="assemblyanalysisbatch",
            name="workflows_a_virify__3194e7_idx",
        ),
        migrations.RemoveIndex(
            model_name="assemblyanalysisbatch",
            name="workflows_a_map_sta_d9f189_idx",
        ),
        migrations.RemoveField(
            model_name="assemblyanalysisbatch",
            name="asa_status",
        ),
        migrations.RemoveField(
            model_name="assemblyanalysisbatch",
            name="map_status",
        ),
        migrations.RemoveField(
            model_name="assemblyanalysisbatch",
            name="virify_status",
        ),
        migrations.AddField(
            model_name="assemblyanalysisbatch",
            name="error_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Chronological log of errors encountered during processing. Each entry contains: timestamp, pipeline, analysis_id, error_type, message",
            ),
        ),
        migrations.AddField(
            model_name="assemblyanalysisbatch",
            name="pipeline_status_counts",
            field=emgapiv2.model_utils.JSONFieldWithSchema(
                blank=True,
                default=dict,
                encoder=emgapiv2.model_utils._PydanticEncoder,
                help_text="Count of analyses in each status per pipeline (asa/virify/map)",
                is_list=False,
                schema=workflows.models.AssemblyAnalysisBatchStatusCounts,
                strict=False,
            ),
        ),
        migrations.AlterField(
            model_name="assemblyanalysisbatchanalysis",
            name="asa_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Assembly Analysis status for this individual analysis",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assemblyanalysisbatchanalysis",
            name="map_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Mobilome Annotation Pipeline status for this individual analysis",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assemblyanalysisbatchanalysis",
            name="virify_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="VIRIfy status for this individual analysis",
                max_length=20,
            ),
        ),
    ]
