# Generated by Django 5.2.7 on 2026-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0010_remove_assemblyanalysisbatch_workflows_a_asa_sta_f1895e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assemblyanalysisbatchanalysis",
            name="contaminant_reference",
            field=models.CharField(
                blank=True,
                help_text="Contaminant reference name used for ASA decontamination.",
                max_length=500,
                null=True,
            ),
        ),
    ]
