# Generated by Django 5.2.7 on 2025-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ena", "0004_alter_sample_additional_accessions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
