# Generated by Django 5.2.7 on 2026-02-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ena", "0005_study_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="ena.study",
            ),
        ),
    ]
