---
version: "3.9"
services:
  slurm_db:
    image: mariadb:latest
    hostname: slurm_db
    container_name: slurm_db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm
      MYSQL_USER: slurm
      MYSQL_PASSWORD: slurm
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    profiles: ["slurm", "all"]
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--connect']
      interval: 2s
      timeout: 2s
      retries: 5
    networks: [slurm]

  slurm_node:
    # A single node instance of slurm (dbd, controller, worker, restd)
    build:
      context: .
    command: ["slurmd"]
    hostname: slurm_node
    container_name: slurm_node
    depends_on:
      slurm_db:
        condition: service_healthy
    volumes:
      - munge:/etc/munge
      - logs:/var/log/slurm
      - jobdir:/opt/jobs
      - "..:/app"
      - "./configs/slurm_prolog.sh:/usr/local/bin/slurm_prolog.sh"
      - "./configs/slurm_epilog.sh:/usr/local/bin/slurm_epilog.sh"
      - "./entrypoints/entrypoint.sh:/usr/local/bin/entrypoint.sh"
      - "./fs/nfs/production:/nfs/production"
      - "./fs/hps:/hps"
      - "./fs/nfs/public:/publicnfs"
      - "./fs/nfs/ftp:/publicftp"
    expose:
      - "6818"
    ports:
      - "6820:6820"
    profiles: ["slurm", "all"]
    networks: [slurm]

volumes:
  db:
  munge:
  logs:
  jobdir:

networks:
  slurm:
    name: slurm
