CREATE SCHEMA proteindb;
SET search_path = proteindb;

-- Ids have gaps: a sequence never hands a number back.
-- The migration sets each START to max(id) + 1 of the migrated data.
CREATE SEQUENCE protein_id_seq    AS bigint;
CREATE SEQUENCE contig_id_seq     AS bigint;
CREATE SEQUENCE occurrence_id_seq AS bigint;

-- The MGYP is 'MGYP' || lpad(id::text, 12, '0').
CREATE TABLE protein_key (
    hash bytea  NOT NULL CHECK (octet_length(hash) = 32),
    id   bigint NOT NULL CHECK (id > 0 AND id < 1000000000000),
    PRIMARY KEY (hash) INCLUDE (id)
) PARTITION BY RANGE (hash);
COMMENT ON COLUMN protein_key.hash IS
    'sha256 of the upper-cased sequence; only A-Z allowed, anything else is rejected (hash contract v1)';

-- 64 partitions on the hash's top 6 bits, the same split as Tier 2: protein_key_00 .. protein_key_3f.
-- Partition p holds the hashes whose first byte is in [4p, 4p + 4).
-- Vacuumed every 100,000 inserts, so that index-only lookups find pages marked all-visible.
DO $$
BEGIN
  FOR p IN 0..63 LOOP
    EXECUTE format(
      'CREATE TABLE protein_key_%s PARTITION OF protein_key FOR VALUES FROM (%s) TO (%s)
         WITH (autovacuum_vacuum_insert_scale_factor = 0, autovacuum_vacuum_insert_threshold = 100000)',
      lpad(to_hex(p), 2, '0'),
      CASE WHEN p = 0  THEN 'MINVALUE' ELSE format('%L::bytea', '\x' || lpad(to_hex(4 * p), 2, '0')) END,
      CASE WHEN p = 63 THEN 'MAXVALUE' ELSE format('%L::bytea', '\x' || lpad(to_hex(4 * (p + 1)), 2, '0')) END);
  END LOOP;
END $$;

-- Registries. Rows are only ever added.
-- An assembly is one analysis of one assembly by one pipeline major.minor.
CREATE TABLE assembly (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accession        text NOT NULL,
    pipeline_version text NOT NULL CHECK (pipeline_version ~ '^[0-9]\.[0-9]$'),  -- the release's decimal(2,1) holds no other
    registered_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (accession, pipeline_version)
);
CREATE TABLE study (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accession text NOT NULL UNIQUE
);
CREATE TABLE biome (
    id      smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lineage text NOT NULL UNIQUE
);
CREATE TABLE gene_caller (
    id      smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    text NOT NULL,
    version text NOT NULL,
    UNIQUE (name, version)
);

-- Staging: written by mgyp-accession in its transaction, emptied by the daily load.
-- A staged protein's id is its id in protein_key.
CREATE TABLE staging_protein (
    id          bigint  PRIMARY KEY,
    hash        bytea   NOT NULL,
    sequence    text    NOT NULL,
    assembly_id integer NOT NULL REFERENCES assembly,      -- the analysis that introduced it
    staged_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON staging_protein (assembly_id);

CREATE TABLE staging_contig (
    id            bigint  PRIMARY KEY DEFAULT nextval('contig_id_seq'),
    assembly_id   integer NOT NULL REFERENCES assembly,
    name          text    NOT NULL,                        -- the pipeline's name, e.g. ERZ101_17
    original_name text,                                    -- the submitted name; NULL when unknown
    length        integer NOT NULL,
    hash          bytea   NOT NULL,                        -- sha256 of the upper-cased contig sequence
    kmer_coverage double precision,
    staged_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (assembly_id, name)
);

CREATE TABLE staging_occurrence (
    id             bigint   PRIMARY KEY DEFAULT nextval('occurrence_id_seq'),
    assembly_id    integer  NOT NULL REFERENCES assembly,
    gene_id        text     NOT NULL,
    protein_id     bigint   NOT NULL,
    contig_id      bigint   NOT NULL REFERENCES staging_contig,
    gene_caller_id smallint NOT NULL REFERENCES gene_caller,
    start_position integer  NOT NULL,
    end_position   integer  NOT NULL,
    strand         smallint NOT NULL CHECK (strand IN (-1, 1)),
    truncation     text     CHECK (truncation IN ('00', '01', '10', '11')),   -- Pyrodigal's partial=XY; NULL for FragGeneScanRS
    staged_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (assembly_id, gene_id)
);
CREATE INDEX ON staging_occurrence (contig_id);

-- Emptied by every daily load, so vacuumed after each one.
ALTER TABLE staging_protein    SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 100000);
ALTER TABLE staging_contig     SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 100000);
ALTER TABLE staging_occurrence SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 100000);

-- One row per daily load attempt.
CREATE TABLE load_log (
    id                    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ingest_date           date NOT NULL,
    status                text NOT NULL CHECK (status IN ('running', 'done', 'failed')),
    started_at            timestamptz NOT NULL DEFAULT now(),
    finished_at           timestamptz,
    assemblies            integer,
    proteins              bigint,
    contigs               bigint,
    occurrences           bigint,
    unresolved_assemblies integer,
    compacted             boolean NOT NULL DEFAULT false,
    message               text
);
-- Keeps a rerun from overwriting a day already loaded into Tier 2.
CREATE UNIQUE INDEX load_log_one_done_per_day ON load_log (ingest_date) WHERE status = 'done';

-- The current writer of Tier 2. One row; its columns are NULL when no one owns it.
CREATE TABLE tier2_owner (
    id              boolean PRIMARY KEY DEFAULT true CHECK (id),
    flow            text CHECK (flow IN ('load')),
    slurm_job_id    bigint,
    slurm_submit_at timestamptz,     -- with the job id, names the job even if SLURM reuses the id
    execution_id    uuid,            -- new for every process that takes ownership
    flow_run_id     uuid,
    acquired_at     timestamptz
);
INSERT INTO tier2_owner DEFAULT VALUES;

-- Roles belong to the cluster, so they are created outside this file, which only grants to them.
-- proteindb_owner owns the schema by applying this file.
GRANT USAGE ON SCHEMA proteindb TO proteindb_accession, proteindb_load, proteindb_read;

GRANT SELECT, INSERT ON protein_key, assembly, gene_caller TO proteindb_accession;
GRANT INSERT ON staging_protein, staging_contig, staging_occurrence TO proteindb_accession;
GRANT SELECT ON staging_contig TO proteindb_accession;
GRANT USAGE ON SEQUENCE protein_id_seq, contig_id_seq, occurrence_id_seq TO proteindb_accession;

GRANT SELECT, DELETE ON staging_protein, staging_contig, staging_occurrence TO proteindb_load;
GRANT SELECT ON assembly, gene_caller TO proteindb_load;
GRANT SELECT, INSERT ON study, biome TO proteindb_load;
GRANT SELECT, INSERT, UPDATE ON load_log TO proteindb_load;
GRANT SELECT, UPDATE ON tier2_owner TO proteindb_load;
GRANT SELECT ON SEQUENCE protein_id_seq TO proteindb_load;

GRANT SELECT ON ALL TABLES IN SCHEMA proteindb TO proteindb_read;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA proteindb TO proteindb_read;

-- Lookups query the partitions directly, and PostgreSQL checks privileges on the table named in the query.
DO $$
BEGIN
  FOR p IN 0..63 LOOP
    EXECUTE format('GRANT SELECT ON protein_key_%s TO proteindb_accession', lpad(to_hex(p), 2, '0'));
  END LOOP;
END $$;

-- SET search_path above applies only to this session, so each role gets the schema at login.
-- The database is named at run time, since it differs between production, dev and the tests.
DO $$
DECLARE
  r text;
BEGIN
  EXECUTE format('GRANT TEMPORARY ON DATABASE %I TO proteindb_accession, proteindb_load', current_database());
  FOREACH r IN ARRAY ARRAY['proteindb_accession', 'proteindb_load', 'proteindb_read'] LOOP
    EXECUTE format('ALTER ROLE %I IN DATABASE %I SET search_path = proteindb', r, current_database());
  END LOOP;
END $$;

-- A client that hangs mid-transaction keeps its new hashes locked, and other jobs meeting them wait.
ALTER ROLE proteindb_accession CONNECTION LIMIT 256;
ALTER ROLE proteindb_accession SET idle_in_transaction_session_timeout = '10min';
ALTER ROLE proteindb_accession SET statement_timeout = '1h';
ALTER ROLE proteindb_accession SET work_mem = '256MB';
ALTER ROLE proteindb_accession SET temp_buffers = '512MB';
ALTER ROLE proteindb_load      SET work_mem = '1GB';
