# Generated by Django 5.2.1 on 2025-06-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0045_assembly_sample"),
        ("genomes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenomeAssemblyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species_rep",
                    models.CharField(
                        blank=True,
                        help_text="Genome accession for species representative",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "mag_accession",
                    models.CharField(
                        blank=True,
                        help_text="Accession for MAG",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genome_links",
                        to="analyses.assembly",
                    ),
                ),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_links",
                        to="genomes.genome",
                    ),
                ),
            ],
            options={
                "db_table": "genome_assembly_link",
                "unique_together": {("genome", "assembly")},
            },
        ),
    ]
