# Generated by Django 5.2.1 on 2025-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genome",
            name="type",
            field=models.CharField(
                choices=[("MAG", "MAG"), ("Isolate", "ISOLATE")], max_length=80
            ),
        ),
    ]
