# Generated by Django 5.2.1 on 2025-09-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0002_genomeassemblylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeassemblylink',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='genomeassemblylink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genomeassemblylink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
