# Generated by Django 5.2.7 on 2025-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomes", "0003_genomeassemblylink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genomeassemblylink",
            name="mag_accession",
            field=models.CharField(
                blank=True, help_text="Accession for MAG", max_length=100, null=True
            ),
        ),
    ]
