# Generated by Django 5.2 on 2025-06-19 10:00

from django.db import migrations, models
import genomes.models.genome


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0004_remove_genomecatalogue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='annotations',
            field=models.JSONField(db_column='annotations', default=genomes.models.genome.Genome.default_annotations.__func__),
        ),
    ]