# Generated by Django 5.2 on 2025-06-19 11:08

import genomes.models.genome
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0004_remove_genomecatalogue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='annotations',
            field=models.JSONField(db_column='annotations', default=genomes.models.genome.default_annotations),
        ),
    ]
