# Generated by Django 5.2.1 on 2025-06-20 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0005_genome_annotations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileFormat',
        ),
        migrations.RemoveField(
            model_name='genomeantismashgccounts',
            name='antismash_genecluster',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='antismash_geneclusters',
        ),
        migrations.AlterUniqueTogether(
            name='genomeantismashgccounts',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomeantismashgccounts',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='cog_matches',
        ),
        migrations.RemoveField(
            model_name='genomecogcounts',
            name='cog',
        ),
        migrations.AlterUniqueTogether(
            name='genomecogcounts',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomecogcounts',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomekeggclass',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='genomekeggclasscounts',
            name='kegg_class',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='kegg_classes',
        ),
        migrations.AlterUniqueTogether(
            name='genomekeggclasscounts',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomekeggclasscounts',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomekeggmodulecounts',
            name='kegg_module',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='kegg_modules',
        ),
        migrations.AlterUniqueTogether(
            name='genomekeggmodulecounts',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomekeggmodulecounts',
            name='genome',
        ),
        migrations.DeleteModel(
            name='GenomeSet',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='genome_set',
        ),
        migrations.RemoveField(
            model_name='genomecatalogue',
            name='downloads',
        ),
        migrations.AddField(
            model_name='genomecatalogue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 16, 15, 2, 943026, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genomecatalogue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genomecatalogue',
            name='description',
            field=models.TextField(blank=True, db_column='DESCRIPTION', help_text='This is a description of the catalogue.', null=True),
        ),
        migrations.AlterField(
            model_name='genomecatalogue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genomecatalogue',
            name='protein_catalogue_description',
            field=models.TextField(blank=True, db_column='PROTEIN_CATALOGUE_DESCRIPTION', help_text='Description of the protein catalogue, if applicable.', null=True),
        ),
        migrations.DeleteModel(
            name='GenomeAntiSmashGC',
        ),
        migrations.DeleteModel(
            name='GenomeAntiSmashGCCounts',
        ),
        migrations.DeleteModel(
            name='GenomeCogCat',
        ),
        migrations.DeleteModel(
            name='GenomeCogCounts',
        ),
        migrations.DeleteModel(
            name='GenomeKeggClass',
        ),
        migrations.DeleteModel(
            name='GenomeKeggClassCounts',
        ),
        migrations.DeleteModel(
            name='GenomeKeggModule',
        ),
        migrations.DeleteModel(
            name='GenomeKeggModuleCounts',
        ),
    ]
