# Generated by Junie for AdditionalContainedGenomes model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0052_update_download_groups_to_pathways_and_systems"),
        ("genomes", "0005_alter_genomeassemblylink_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalContainedGenomes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("containment", models.FloatField(blank=True, null=True)),
                ("cani", models.FloatField(blank=True, db_column="cANI", null=True)),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_contained_genomes",
                        to="analyses.assembly",
                    ),
                ),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_contained_genomes",
                        to="genomes.genome",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_contained_genomes",
                        to="analyses.run",
                    ),
                ),
            ],
            options={
                "db_table": "additional_contained_genomes",
                "unique_together": {("run", "genome", "assembly")},
            },
        ),
        migrations.AddIndex(
            model_name="additionalcontainedgenomes",
            index=models.Index(fields=["run"], name="add_cont_run_idx"),
        ),
        migrations.AddIndex(
            model_name="additionalcontainedgenomes",
            index=models.Index(fields=["genome"], name="add_cont_genome_idx"),
        ),
        migrations.AddIndex(
            model_name="additionalcontainedgenomes",
            index=models.Index(fields=["assembly"], name="add_cont_assembly_idx"),
        ),
    ]
