# Generated by Django 5.2.7 on 2026-05-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0006_additionalcontainedgenomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='catalogue',
            field=models.ForeignKey(db_column='genome_catalogue', on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='genomes.genomecatalogue'),
        ),
    ]
