# Generated by Django 5.2.7 on 2026-05-28 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0007_alter_genome_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomecatalogue',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
