# Generated by Django 5.2.7 on 2026-07-02 15:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomes", "0008_alter_genomecatalogue_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenomeSearchIndex",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("sourmash", "Sourmash"),
                            ("branchwater", "Branchwater"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                            ("FAILED", "Failed"),
                        ],
                        default="BUILDING",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("ksize", models.PositiveSmallIntegerField(default=31)),
                ("moltype", models.CharField(default="DNA", max_length=16)),
                ("scaled", models.PositiveIntegerField(blank=True, null=True)),
                ("artifact_path", models.CharField(max_length=500)),
                ("manifest_path", models.CharField(blank=True, max_length=500)),
                ("genome_count", models.PositiveIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="search_indexes",
                        to="genomes.genomecatalogue",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "catalogue__catalogue_id",
                    "backend",
                    "ksize",
                    "-created_at",
                ),
            },
        ),
        migrations.CreateModel(
            name="SourmashSearchJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL_SUCCESS", "Partial success"),
                            ("FAILED", "Failed"),
                            ("NO_RESULTS", "No results"),
                        ],
                        default="RECEIVED",
                        max_length=32,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("submitted_by", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("raw_results_archive_path", models.CharField(blank=True, max_length=500)),
                ("error_summary", models.TextField(blank=True)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="SourmashSearchJobItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("NO_RESULTS", "No results"),
                        ],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                ("query_original_name", models.CharField(max_length=255)),
                ("query_staged_path", models.CharField(max_length=500)),
                ("task_result_id", models.CharField(blank=True, max_length=64)),
                ("raw_csv_path", models.CharField(blank=True, max_length=500)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="items",
                        to="genomes.sourmashsearchjob",
                    ),
                ),
                (
                    "search_index",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="job_items",
                        to="genomes.genomesearchindex",
                    ),
                ),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.AddConstraint(
            model_name="genomesearchindex",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("catalogue", "backend", "ksize", "moltype"),
                name="unique_active_search_index_per_catalogue_backend",
            ),
        ),
    ]
