---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: emgapiv2-hl-exp
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: proxy-config
      namespace: emgapiv2-hl-exp
    data:
      HTTP_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
      HTTPS_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
      http_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
      https_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
      no_proxy: "localhost,.cluster.local"
  ###############################
  #### APP/API               ####
  ###############################
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: emgapi-vol-nfs
      namespace: emgapiv2-hl-exp
    spec:
      capacity:
        storage: 10Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      mountOptions:
        - nfsvers=3
      nfs:
        server: hh-isi-srv-vlan1496.ebi.ac.uk
        path: /ifs/public/rw/metagenomics/mgnify/deployments/apiv2/DEV
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: emgapi-volume-claim-3
      namespace: emgapiv2-hl-exp
    spec:
      storageClassName: ""
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 3Gi
      volumeName: emgapi-vol-nfs
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: emgapi-vol-nfs-services
      namespace: emgapiv2-hl-exp
    spec:
      capacity:
        storage: 10Gi
      volumeMode: Filesystem
      accessModes:
        - ReadOnlyMany
      mountOptions:
        - nfsvers=3
      nfs:
        server: hh-isi-srv-vlan1496.ebi.ac.uk
        path: /ifs/public/services/metagenomics/results
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: emgapi-services-volume-claim-1
      namespace: emgapiv2-hl-exp
    spec:
      storageClassName: ""
      accessModes:
        - ReadOnlyMany
      resources:
        requests:
          storage: 3Gi
      volumeName: emgapi-vol-nfs-services

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: emgapi-config
      namespace: emgapiv2-hl-exp
    data:
      DJANGO_SETTINGS_MODULE: "emgapiv2.settings"
      PREFECT_API_URL: "http://prefect-server.emgapiv2-hl-exp.svc.cluster.local:4200/api"
      PREFECT_HOME: "/app/data/prefect"
      EMG_SLURM__SHARED_FILESYSTEM_ROOT_ON_SLURM: "/nfs/public/rw/metagenomics/mgnify/deployments/apiv2/DEV"
      EMG_SLURM__SHARED_FILESYSTEM_ROOT_ON_SERVER: "/app/data"
      EMG_SLURM__SAMPLESHEET_EDITING_ALLOWED_INSIDE: "/nfs/production/rdf/metagenomics/projects/automation/slurm_workdir"
      EMG_SLURM__SAMPLE_EDITING_PATH_FROM_SHARED_FILESYSTEM: "temporary_samplesheet_edits"
      EMG_SLURM__DEFAULT_WORKDIR: "/nfs/production/rdf/metagenomics/projects/automation/slurm_workdir"
      EMG_SERVICE_URLS__TRANSFER_SERVICES_URL_ROOT: "https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: emgapiv2-app
      namespace: emgapiv2-hl-exp
      labels:
        app: emgapiv2
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: emgapi
      template:
        metadata:
          labels:
            app: emgapi
        spec:
          securityContext:
            runAsUser: 7123
            runAsGroup: 1347
          volumes:
            - name: emgapi-app-storage
              persistentVolumeClaim:
                claimName: emgapi-volume-claim-3
            - name: emgapi-results-storage
              persistentVolumeClaim:
                claimName: emgapi-services-volume-claim-1
          containers:
            - image: quay.io/microbiome-informatics/emgapiv2:ebi-wp-k8s-hl
              imagePullPolicy: Always
              name: emgapi
              envFrom:
                - secretRef:
                    name: emgapi-secret
                - configMapRef:
                    name: emgapi-config
                - configMapRef:
                    name: proxy-config
              env:
                - name: PREFECT_API_AUTH_STRING
                  valueFrom:
                    secretKeyRef:
                      key: PREFECT_SERVER_API_AUTH_STRING
                      name: emgapi-secret
              ports:
                - containerPort: 8000
                  name: gunicorn
              volumeMounts:
                - mountPath: "/app/data"
                  name: emgapi-app-storage
                - mountPath: "/results"
                  name: emgapi-results-storage
          imagePullSecrets:
            - name: quay-pull-secret
          nodeSelector:
            mgnify.org/ebi-db-pgsql-hlvm-090-open: "true"
  - apiVersion: v1
    kind: Service
    metadata:
      name: emgapiv2
      namespace: emgapiv2-hl-exp
      labels:
        app: emgapi
    spec:
      type: NodePort
      selector:
        app: emgapi
      ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: emgapi-ingress
      namespace: emgapiv2-hl-exp
      annotations:
        kubernetes.io/ingress.class: "nginx"
    spec:
      rules:
        - host: apiv2-dev.mgnify.org
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: emgapiv2
                    port:
                      number: 8000

  ###############################
  #### PREFECT SERVER        ####
  ###############################
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: prefect-server
      namespace: emgapiv2-hl-exp
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: prefect-server
      template:
        metadata:
          labels:
            app: prefect-server
        spec:
          containers:
            - name: prefect-server
              image: prefecthq/prefect:3.2.12-python3.12
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2000m"
              imagePullPolicy: IfNotPresent
              command: ["/opt/prefect/entrypoint.sh"]
              args: ["prefect", "server", "start"]
              envFrom:
                - configMapRef:
                    name: proxy-config
              env:
                - name: PREFECT_UI_URL
                  value: http://prefect-dev.mgnify.org
                - name: PREFECT_API_URL
                  value: http://prefect-dev.mgnify.org/api
                - name: PREFECT_UI_API_URL
                  value: http://prefect-dev.mgnify.org/api
                - name: PREFECT_SERVER_API_HOST
                  value: 0.0.0.0
                - name: PREFECT_API_DATABASE_CONNECTION_URL
                  valueFrom:
                    secretKeyRef:
                      key: PREFECT_API_DATABASE_CONNECTION_URL
                      name: emgapi-secret
                - name: PREFECT_SERVER_API_AUTH_STRING
                  valueFrom:
                    secretKeyRef:
                      key: PREFECT_SERVER_API_AUTH_STRING
                      name: emgapi-secret
                - name: EXTRA_PIP_PACKAGES
                  value: httpx[cli] nextflowpy
                - name: PREFECT_LOCAL_STORAGE_PATH
                  value: /app/data/prefect/storage
                - name: PREFECT_LOGGING_LEVEL
                  value: DEBUG
                - name: CURL_CA_BUNDLE  # for prefect-slack
                  value: ""
                - name: PYTHONHTTPSVERIFY  # for prefect-slack
                  value: "false"
              ports:
                - containerPort: 4200
          nodeSelector:
            mgnify.org/ebi-db-pgsql-hlvm-090-open: "true"
  - apiVersion: v1
    kind: Service
    metadata:
      name: prefect-server
      namespace: emgapiv2-hl-exp
    spec:
      type: ClusterIP
      ports:
        - port: 4200
          targetPort: 4200
      selector:
        app: prefect-server

  #### Serve prefect to auth'd users (prefect handles the auth via http basic) ####
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: prefect-ingress
      namespace: emgapiv2-hl-exp
    spec:
      ingressClassName: nginx
      rules:
        - host: prefect-dev.mgnify.org
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: prefect-server
                    port:
                      number: 4200
