---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: emgapiv2-hl-exp
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: proxy-config
      namespace: emgapiv2-hl-exp
    data:
      HTTP_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
      HTTPS_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
      http_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
      https_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
      no_proxy: "localhost,.cluster.local"
  ###############################
  #### APP/API               ####
  ###############################
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: emgapi-vol-nfs
      namespace: emgapiv2-hl-exp
    spec:
      capacity:
        storage: 10Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      mountOptions:
        - nfsvers=3
      nfs:
        server: hh-isi-srv-vlan1496.ebi.ac.uk
        path: /ifs/public/rw/metagenomics/mgnify/deployments/apiv2/DEV
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: emgapi-volume-claim-3
      namespace: emgapiv2-hl-exp
    spec:
      storageClassName: ""
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 3Gi
      volumeName: emgapi-vol-nfs

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: emgapi-config
      namespace: emgapiv2-hl-exp
    data:
      DJANGO_SETTINGS_MODULE: "emgapiv2.settings"
      PREFECT_API_URL: "http://prefect-dev.mgnify.org/api"
      PREFECT_HOME: "/app/data/prefect"
      # PREFECT_LOCAL_STORAGE_PATH: "/app/data/prefect/storage"


  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: emgapiv2-app
      namespace: emgapiv2-hl-exp
      labels:
        app: emgapiv2
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: emgapi
      template:
        metadata:
          labels:
            app: emgapi
        spec:
          securityContext:
            runAsUser: 7123
            runAsGroup: 1347
          volumes:
            - name: emgapi-app-storage
              persistentVolumeClaim:
                claimName: emgapi-volume-claim-3
          containers:
            - image: quay.io/microbiome-informatics/emgapiv2:ebi-wp-k8s-hl
              imagePullPolicy: Always
              name: emgapi
              envFrom:
                - secretRef:
                    name: emgapi-secret
                - configMapRef:
                    name: emgapi-config
                - configMapRef:
                    name: proxy-config
              ports:
                - containerPort: 8000
                  name: gunicorn
              volumeMounts:
                - mountPath: "/app/data"
                  name: emgapi-app-storage
          imagePullSecrets:
            - name: quay-pull-secret
  - apiVersion: v1
    kind: Service
    metadata:
      name: emgapiv2
      namespace: emgapiv2-hl-exp
      labels:
        app: emgapi
    spec:
      type: NodePort
      selector:
        app: emgapi
      ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: emgapi-ingress
      namespace: emgapiv2-hl-exp
      annotations:
        kubernetes.io/ingress.class: "nginx"
    spec:
      rules:
        - host: apiv2-dev.mgnify.org
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: emgapiv2
                    port:
                      number: 8000

  ###############################
  #### DATABASES (temporary) ####
  ###############################

  ## PREFECT DB ##
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres-prefect
      namespace: emgapiv2-hl-exp
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgres-prefect
      template:
        metadata:
          labels:
            app: postgres-prefect
        spec:
          containers:
            - name: postgres-prefect
              image: postgres:latest
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_PREFECT_USER
                      name: emgapi-secret
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_PREFECT_PASSWORD
                      name: emgapi-secret
                - name: POSTGRES_DB
                  value: "prefect"
              ports:
                - containerPort: 5432
          volumes:
            - name: postgres-prefect-storage
              persistentVolumeClaim:
                claimName: postgres-prefect-pv-claim
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgres-prefect-pv-claim
      namespace: emgapiv2-hl-exp
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgres-prefect
      namespace: emgapiv2-hl-exp
    spec:
      ports:
        - port: 5432
      selector:
        app: postgres-prefect
      clusterIP: None

  ## APP DB ##
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres-app
      namespace: emgapiv2-hl-exp
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgres-app
      template:
        metadata:
          labels:
            app: postgres-app
        spec:
          containers:
            - name: postgres-app
              image: postgres:latest
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_APP_USER
                      name: emgapi-secret
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_APP_PASSWORD
                      name: emgapi-secret
                - name: POSTGRES_DB
                  value: "emg"
              ports:
                - containerPort: 5432
          volumes:
            - name: postgres-app-storage
              persistentVolumeClaim:
                claimName: postgres-app-pv-claim
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgres-app
      namespace: emgapiv2-hl-exp
    spec:
      type: NodePort
      selector:
        app: postgres-app
      ports:
        - port: 5432
          nodePort: 30100
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgres-app-pv-claim
      namespace: emgapiv2-hl-exp
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi

  ###############################
  #### PREFECT SERVER        ####
  ###############################
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: prefect-server
      namespace: emgapiv2-hl-exp
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: prefect-server
      template:
        metadata:
          labels:
            app: prefect-server
        spec:
          containers:
            - name: prefect-server
              image: prefecthq/prefect:2-latest
              command: ["/opt/prefect/entrypoint.sh"]
              args: ["prefect", "server", "start"]
              envFrom:
                - configMapRef:
                    name: proxy-config
              env:
                - name: PREFECT_UI_URL
                  value: http://prefect-dev.mgnify.org/api
                - name: PREFECT_API_URL
                  value: http://prefect-dev.mgnify.org/api
                - name: PREFECT_UI_API_URL
                  value: http://prefect-dev.mgnify.org/api
                - name: PREFECT_SERVER_API_HOST
                  value: 0.0.0.0
                - name: PREFECT_API_DATABASE_CONNECTION_URL
                  valueFrom:
                    secretKeyRef:
                      key: PREFECT_API_DATABASE_CONNECTION_URL
                      name: emgapi-secret
                - name: EXTRA_PIP_PACKAGES
                  value: httpx[cli] nextflowpy
                - name: PREFECT_LOCAL_STORAGE_PATH
                  value: /app/data/prefect/storage
              ports:
                - containerPort: 4200

  - apiVersion: v1
    kind: Service
    metadata:
      name: prefect-server
      namespace: emgapiv2-hl-exp
      labels:
        app: prefect-server
    spec:
      type: NodePort
      ports:
        - name: prefect
          port: 4200
          targetPort: 4200
          protocol: TCP
      selector:
        app: prefect-server

  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: prefect-ingress
      namespace: emgapiv2-hl-exp
      annotations:
        kubernetes.io/ingress.class: "nginx"
    spec:
      rules:
        - host: prefect-dev.mgnify.org
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: prefect-server
                    port:
                      number: 4200
