import csv
from pathlib import Path
from typing import Iterable, List

from prefect import get_run_logger

from analyses.models import Analysis
from workflows.flows.analyse_study_tasks.shared.analysis_states import AnalysisStates
from workflows.models import (
    AssemblyAnalysisBatchAnalysis,
    AssemblyAnalysisPipelineStatus,
)
from workflows.prefect_utils.flows_utils import django_db_task as task


def _read_report_csv(report_csv_path: Path) -> dict[str, str]:
    report_entries = {}
    with report_csv_path.open(mode="r") as file_handle:
        for row in csv.reader(file_handle, delimiter=","):
            assembly_accession, info = row
            report_entries[assembly_accession] = info
    return report_entries


def parse_asa_end_of_run_reports(
    qc_failed_csv: Path,
    analysed_assemblies_csv: Path,
    logger,
) -> tuple[dict[str, str], dict[str, str]]:
    qc_failed_assemblies = {}
    if qc_failed_csv.is_file():
        logger.info("Reading qc failed assemblies...")
        qc_failed_assemblies = _read_report_csv(qc_failed_csv)

    if not analysed_assemblies_csv.is_file():
        raise ValueError(
            "The end of run execution CSV file is missing. "
            f"Expected path: {analysed_assemblies_csv}"
        )

    analysed_assemblies = _read_report_csv(analysed_assemblies_csv)
    return qc_failed_assemblies, analysed_assemblies


def update_asa_batch_relations_from_reports(
    batch_relations: Iterable[AssemblyAnalysisBatchAnalysis],
    qc_failed_assemblies: dict[str, str],
    analysed_assemblies: dict[str, str],
    logger,
) -> list[AssemblyAnalysisBatchAnalysis]:
    relations_to_update = []

    for batch_relation in batch_relations:
        analysis = batch_relation.analysis
        assembly_accession = analysis.assembly.first_accession

        if assembly_accession in analysed_assemblies:
            logger.info(f"{analysis} marked as analyzed in the end of run CSV.")
            batch_relation.asa_status = AssemblyAnalysisPipelineStatus.COMPLETED
        else:
            if assembly_accession in qc_failed_assemblies:
                logger.error(f"QC failed - {analysis}")
            else:
                logger.error(f"Assembly {analysis} missing from CSV.")
            batch_relation.asa_status = AssemblyAnalysisPipelineStatus.FAILED

        relations_to_update.append(batch_relation)

    return relations_to_update


def update_analyses_from_asa_reports(
    analyses: Iterable[Analysis],
    qc_failed_assemblies: dict[str, str],
    analysed_assemblies: dict[str, str],
    analysed_assemblies_csv: Path,
    logger,
) -> list[Analysis]:
    analyses_to_update = []

    for analysis in analyses:
        assembly_accession = analysis.assembly.first_accession

        if assembly_accession in analysed_assemblies:
            logger.info(
                f"{assembly_accession} marked as analyzed in the end of run CSV."
            )
            continue

        if assembly_accession in qc_failed_assemblies:
            logger.error(f"QC failed - {assembly_accession}")
            reason = qc_failed_assemblies[assembly_accession]
        else:
            logger.error(f"Assembly {assembly_accession} missing from CSV.")
            reason = f"Assembly missing from {analysed_assemblies_csv}."

        analysis.mark_status(
            AnalysisStates.ANALYSIS_QC_FAILED,
            set_status_as=True,
            save=False,
            reason=reason,
        )
        analyses_to_update.append(analysis)

    return analyses_to_update


@task()
def set_post_assembly_analysis_states(
    assembly_current_outdir: Path, assembly_analyses_ids: List[int]
):
    """
    This function processes the end-of-execution reports generated by the assembly analysis pipeline
    to determine the outcome of each assembly and updates their status accordingly.

    TODO: this method is doing way too much, it's hard to follow and it has loads of side-effects that affect the
          flow of data. I think we need more atomic operations scatter in each pipeline batch.

    The pipeline produces two CSV files:
    - qc_failed_assemblies.csv: Lists assemblies that failed QC checks (assemblyID, reason)
    - analysed_assemblies.csv: Lists assemblies that completed successfully (assemblyID, info)

    Logic flow:
    1. Read QC failures from qc_failed_assemblies.csv if it exists
    2. Read successful analyses from analysed_assemblies.csv (raises error if the file is missing)
    3. For each assembly analysis:
    - If assembly is in QC failures: Mark workflow_status as FAILED and set status to ANALYSIS_QC_FAILED
    - If assembly is in successful analyses: Mark workflow_status as COMPLETED
    - If assembly is in neither list: Mark workflow_status as FAILED with unknown reason
    4. Bulk update all analyses to minimize database operations

    :param assembly_current_outdir: Path to the directory containing the pipeline output
    :param assembly_analyses_ids: List of assembly analyses IDs to process
    :raises ValueError: If the analysed_assemblies.csv file is missing (catastrophic failure)
    """
    # The pipeline produces top-level end-of-execution reports, which contain
    # the list of the assemblies that were completed and those that were not.
    # Similar to the amplicon pipeline

    logger = get_run_logger()

    qc_failed_csv = assembly_current_outdir / "qc_failed_assemblies.csv"
    analysed_assemblies_csv = assembly_current_outdir / "analysed_assemblies.csv"
    qc_failed_assemblies, analysed_assemblies = parse_asa_end_of_run_reports(
        qc_failed_csv, analysed_assemblies_csv, logger=logger
    )

    batch_relations = AssemblyAnalysisBatchAnalysis.objects.filter(
        analysis_id__in=assembly_analyses_ids
    ).select_related("analysis__assembly")

    relations_to_update = update_asa_batch_relations_from_reports(
        batch_relations,
        qc_failed_assemblies,
        analysed_assemblies,
        logger=logger,
    )

    analyses_to_update = update_analyses_from_asa_reports(
        [batch_relation.analysis for batch_relation in batch_relations],
        qc_failed_assemblies,
        analysed_assemblies,
        analysed_assemblies_csv,
        logger=logger,
    )

    # Bulk update - slightly gentler on the DB
    AssemblyAnalysisBatchAnalysis.objects.bulk_update(
        relations_to_update, ["asa_status"]
    )
    Analysis.objects.bulk_update(analyses_to_update, ["status"])
